config/routes.rb
Rails.application.routes.draw do
  resources :eduzones

      root 'eduzones#index'
      get '/about',   :to => 'eduzones#about'
      get '/service',   :to => 'eduzones#service'
      get '/course',   :to => 'eduzones#course'
      get '/contact',   :to => 'eduzones#contact'

end

app/models/eduzone.rb
class Eduzone < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/eduzones_controller.rb
class EduzonesController < ApplicationController
  before_action :set_eduzone, only: [:show, :edit, :update, :destroy]

  # GET /eduzones
  # GET /eduzones.json
  def index
    @eduzones = Eduzone.all
  end

  # GET /eduzones/1
  # GET /eduzones/1.json
  def show
  end

  # GET /eduzones/new
  def new
    @eduzone = Eduzone.new
  end

  # GET /eduzones/1/edit
  def edit
  end

  # POST /eduzones
  # POST /eduzones.json
  def create
    @eduzone = Eduzone.new(eduzone_params)

    respond_to do |format|
      if @eduzone.save
        format.html { redirect_to @eduzone, notice: 'Eduzone was successfully created.' }
        format.json { render :show, status: :created, location: @eduzone }
      else
        format.html { render :new }
        format.json { render json: @eduzone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eduzones/1
  # PATCH/PUT /eduzones/1.json
  def update
    respond_to do |format|
      if @eduzone.update(eduzone_params)
        format.html { redirect_to @eduzone, notice: 'Eduzone was successfully updated.' }
        format.json { render :show, status: :ok, location: @eduzone }
      else
        format.html { render :edit }
        format.json { render json: @eduzone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eduzones/1
  # DELETE /eduzones/1.json
  def destroy
    @eduzone.destroy
    respond_to do |format|
      format.html { redirect_to eduzones_url, notice: 'Eduzone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_eduzone
      @eduzone = Eduzone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def eduzone_params
      params[:eduzone]
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/helpers/eduzones_helper.rb
module EduzonesHelper
end

app/views/eduzones/_form.html.erb
<%= form_for(@eduzone) do |f| %>
  <% if @eduzone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@eduzone.errors.count, "error") %> prohibited this eduzone from being saved:</h2>

      <ul>
      <% @eduzone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eduzones/about.html.erb
<h1>About Us</h1>
<p>
	Hello guys 
</p>

app/views/eduzones/contact.html.erb
<h1>Contacts Us</h1>
<p>
	Hello guys 
</p>

<div id="page2" class="content">
<div class="container_12">
	
<div class="grid_3">
					<div class="box maxheight">
						<img src="[mfassetpath]/box_img1.jpg" alt="">
						<div class="text1"><a href="#">Raju Shah</a></div>senior manager
						<div class="socials1">
							<a href="#"></a>
							<a href="#"></a>
							<a href="#"></a>
							<a href="#"></a>
						</div>
					</div>
				</div>


				<div class="grid_3">
					<div class="box maxheight">
						<img src="[mfassetpath]/box_img2.jpg" alt="">
						<div class="text1"><a href="#">Anton Stegner</a></div> manager
						<div class="socials1">
							<a href="#"></a>
							<a href="#"></a>
							<a href="#"></a>
							<a href="#"></a>
						</div>
					</div>
				</div>
			</div>
	
		</div>

app/views/eduzones/course.html.erb
<!DOCTYPE html>
<html lang="en">

<h1>Courses Offered</h1>

	<table> 
        <div class='main'>
            <table class="table ">
              <th>MEDICINE</th>
              <th>ENGINEERING</th>
              <th>MEDICINE</th>

              <tr>
              	<td>AIIMS</td>
              	<td>NIT</td>
              	<td>NIT</td>
              </tr>
              <tr>
              	<td>AIIMSss</td>
              	<td>NITss</td>
              	<td>NIT</td>
              </tr>
              <tr>
              	<td>AIIMS</td>
              	<td>NIT</td>
              	<td>NIT</td>
              </tr>

              
            </table>
        </div>
     </table>      

</head>

app/views/eduzones/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
 <title>EduZone App</title>  
</head>
    <body>  
        <center><p>
            A dream doesn't become reality through magic;</br>
               it takes sweat, </br>determination and hard work.
        </p> </center> 
        <div id="wrapper">
            Piece of text inside a 500px width div centered on the page
        </div>
        <section class="header-15-sub bg-midnight-blue">
         	<div class="background">&nbsp;</div>
                <div class="span6 offset1 player-wrapper">
                    <div class="player">
                           <iframe src="http://player.vimeo.com/video/29568236?color=3498db" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
                    </div>
                    
                </div>
            </div> 
        </section>    
	</body>
</html>

app/views/eduzones/new.html.erb
<h1>New Eduzone</h1>

<%= render 'form' %>

<%= link_to 'Back', eduzones_path %>

app/views/eduzones/service.html.erb
<h1>Services</h1>
<p>
	we provide following Preparation Classes
</p>

 <h1>Preparation classes<h1>
 	<ul>
 	<h4><a href="https://sat.collegeboard.org/home"><li>SAT</li></a></h4>
 	<h4><a href="http://www.mba.com/global"><li>GMAT</li></a></h4>
 	<h4><a href="http://www.ets.org/gre"><li>GRE</li></a></h4>
</ul>
 

app/views/eduzones/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_eduzone_path(@eduzone) %> |
<%= link_to 'Back', eduzones_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
  <title>EduZone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>	
  <%= image_tag 'images.jpeg' %>
		<div class="row">
			<div class="span6">
        <center><h1>Welcome to Edu Zone consultancy</h1></center>
				<div class="nav nav-tabs">
          <li><%= link_to "Home", root_path, class: "btn btn-primary" %></li>
          <li><%= link_to "About", about_path, class: "btn btn-primary" %></li>	
          <li><%= link_to "Services", service_path, class: "btn btn-primary"%></li>
          <li><%= link_to "Courses", course_path, class: "btn btn-primary"%></li>
          <li><%= link_to "Contacts", contact_path, class: "btn btn-primary"%></li> 
        </div>
      </div>
    </div>
  </br>
  <div class="container">
<%= yield %>
</div>
</body>
</html>